### ISSUE TITLE
Comparing doesn't work in Linux virtual environment

### ISSUE THREAD

**Issue by oikajo** [F-Secure/change-analyzer#5]
`ca-compare` doesn't work in Linux virtual environment. Current workaround is to deactivate virtual environment and use absolute paths to call python and use change_analyzer/sequences_diff.py file.

Error message from venv compare:
```
ca-compare --sequence1_folder 2021_10_11-15_21_55 --sequence2_folder 2021_10_11-15_24_33

Traceback (most recent call last):
File "/home/oikajo/source/change-analyzer/.venv/bin/ca-compare", line 8, in <module>
sys.exit(main())
File "/home/oikajo/source/change-analyzer/.venv/lib/python3.7/site-packages/change_analyzer/sequences_diff.py", line 287, in main
SequencesDiff(sequence1_folder=args.sequence1_folder, sequence2_folder=args.sequence2_folder)
File "/home/oikajo/source/change-analyzer/.venv/lib/python3.7/site-packages/change_analyzer/sequences_diff.py", line 50, in __init__
self.write_to_report()
File "/home/oikajo/source/change-analyzer/.venv/lib/python3.7/site-packages/change_analyzer/sequences_diff.py", line 244, in write_to_report
template = env.get_template("Log_template.html")
File "/home/oikajo/source/change-analyzer/.venv/lib/python3.7/site-packages/jinja2/environment.py", line 997, in get_template
return self._load_template(name, globals)
File "/home/oikajo/source/change-analyzer/.venv/lib/python3.7/site-packages/jinja2/environment.py", line 958, in _load_template
template = self.loader.load(self, name, self.make_globals(globals))
File "/home/oikajo/source/change-analyzer/.venv/lib/python3.7/site-packages/jinja2/loaders.py", line 125, in load
source, filename, uptodate = self.get_source(environment, name)
File "/home/oikajo/source/change-analyzer/.venv/lib/python3.7/site-packages/jinja2/loaders.py", line 214, in get_source
raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: Log_template.html
```

**Comment by oikarinen-fs** [comment]
Fixed in: https://github.com/F-Secure/change-analyzer/commit/108582d0feadaffc725a1fc23aea5afb210760bf.
